# Generated by Django 4.2.1 on 2023-09-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=12, null=True)),
                ('endereco', models.CharField(max_length=150, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=5, null=True)),
                ('cpf', models.CharField(max_length=15, null=True, verbose_name='CPF/CNPJ (Obrigatório para emissão de Nota Fiscal)')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
