# Generated by Django 4.2.1 on 2023-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_campo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(default=1, upload_to='arquivos/'),
            preserve_default=False,
        ),
    ]
