# Generated by Django 4.2.1 on 2023-08-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_campo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.campo'),
        ),
    ]
