# Generated by Django 4.2.1 on 2023-08-14 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=150, verbose_name='Título')),
                ('contato', models.CharField(max_length=100)),
                ('detalhes', models.TextField()),
                ('data_criado', models.DateTimeField()),
                ('data_fechado', models.DateTimeField(blank=True)),
                ('tecnico', models.CharField(max_length=100)),
                ('arquivo', models.FileField(blank=True, upload_to='arquivos/')),
                ('status', models.CharField(max_length=50)),
                ('atividade', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
