# Generated by Django 4.2.1 on 2023-08-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_tecnico_alter_chamados_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.status'),
        ),
    ]
