# Generated by Django 4.2.1 on 2023-08-15 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_status_alter_chamados_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='data_criado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 19, 3, 16, 823066, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_fechado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 19, 3, 16, 823066, tzinfo=datetime.timezone.utc)),
        ),
    ]
