# Generated by Django 4.2.1 on 2023-08-16 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_alter_chamados_data_criado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='resolucao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='assunto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_criado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 0, 46, 478399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_fechado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 0, 46, 478399, tzinfo=datetime.timezone.utc)),
        ),
    ]
