# Generated by Django 4.2.1 on 2023-08-18 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_chamados_resolucao_alter_chamados_assunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='empresa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_criado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 18, 26, 16, 408383, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_fechado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 18, 26, 16, 408383, tzinfo=datetime.timezone.utc)),
        ),
    ]
