# Generated by Django 4.2.1 on 2023-08-25 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_chamados_empresa_alter_chamados_data_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='data_criado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 12, 12, 28, 194851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_fechado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 12, 12, 28, 194851, tzinfo=datetime.timezone.utc)),
        ),
    ]
