# Generated by Django 4.2.1 on 2023-08-25 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_alter_chamados_data_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='arquivo',
            field=models.FileField(null=True, upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='atividade',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_criado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 12, 26, 19, 891674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_fechado',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 12, 26, 19, 891674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='resolucao',
            field=models.TextField(null=True),
        ),
    ]
