# Generated by Django 4.2.1 on 2023-08-25 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_alter_chamados_arquivo_alter_chamados_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='data_criado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_fechado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
